### ISSUE TITLE
Permission denied for ultimate boot cd

### ISSUE THREAD

**Issue by Darks1de42** [netbootxyz/netboot.xyz#1277]
**Describe the bug**
UBCD Fails booting with the permission denied error.

**To Reproduce**
1. Boot Ultimate Boot CD.

**Expected behavior**
Ultimate Boot CD is booting and starting.

**Screenshots**
![VirtualBox_netboot_05_08_2023_12_56_37](https://github.com/netbootxyz/netboot.xyz/assets/48830356/eab0b3ba-a6c6-42df-afc4-ca57646e36f0)

**Comment by matchuek** [comment]
this may be a clue:

              GIve it a try now, the iPXE root ca cross signing cert had expired and is now fixed.

_Originally posted by @antonym in https://github.com/netbootxyz/netboot.xyz/issues/86#issuecomment-190383312_

**Comment by Thomas-Busch-Waterloo** [comment]
I can confirm this is still an issue,

![image](https://github.com/netbootxyz/netboot.xyz/assets/19546812/dbd09061-ba08-4b21-803e-b85831db579f)

**Comment by shalak** [comment]
I'm facing similar issue when using my local asset cache:
![image](https://github.com/netbootxyz/netboot.xyz/assets/1536554/b0514d39-37c6-4d95-b868-aa9eca9a1bc6)
The cert on `https:/netbootxyz.mydomain.net/` is valid, signed by Let's Encrypt

I entered the iPXE shell and run `show unixtime` (and converted it via`date --date=@$((0x65a43aa6))`) to verify that the sytem time is correct - it is. Running `curl https://netbootxyz-nginx.mydomain.net/ubuntu-squash/releases/download/22.04.3-7e94379b/vmlinuz` downloads the vmlinuz file with no issues.

As this probably is a different issue, I've taken a liberty of creating a [separate issue](https://github.com/netbootxyz/netboot.xyz/issues/1398) for it.

**Comment by Furbynat0r1122** [comment]
Here is the fix:

Just Replace the Mirror in the utils-pcbios-64.ipxe menu:

:ubcd
set util_path http://pharry.org/data/ubcd539.iso
set util_file ubcd539.iso
set util_version 539
goto boot_memdisk

**Comment by antonym** [comment]
Try the latest rolling build, I was able to load it right up, it should work better with Let's Encrypt Certs now.

https://twitter.com/ipxe/status/1758124717477593405

**Comment by shalak** [comment]
I'm struggling to find the rolling build docker image... I guess I'll have to wait until it's officially released 🤔

**Comment by antonym** [comment]
The latest from the netboot.xyz download page is always rolling.

**Comment by shalak** [comment]
Hmm, the `ghcr.io/netbootxyz/netbootxyz:latest` runs netbootxyz `v2.0.76` and does not work with Let's Encrypt certs

**Comment by pctripsesp** [comment]
I downloaded the latest from `https://netboot.xyz/docs/booting/usb` and still same error
