### ISSUE TITLE
[BUG] win_base_url not listed when booting to netbootxyz windows menu

### ISSUE THREAD

**Issue by deffcolony** [netbootxyz/netboot.xyz#1344]
# Describe the bug
When i tried to set the base url for **win_base_url** at **boot.cfg** it does not get displayed in the boot menu for windows... i have to type the url manually everytime i boot to netbootxyz menu

# Environment
Docker on a ubuntu server

# To Reproduce
1. Visit your netbootxyz dashboard
2. Go to Menus > boot.cfg
3. Add or replace the following line set win_base_url http://YOUR_NETBOOTXYZ_IP:/winpe
4. Do a networkboot and go to Distributions: > Windows

I use the following docker-compose.yml maybe this could help?

```yaml
version: "3.8"

services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
#      MENU_VERSION: 1.9.9 #optional unset is latest version
      PORT_RANGE: 30000:30010 #optional
      SUBFOLDER: / #optional
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - 9170:3000
      - 9171:69/udp
      - 9172:80 #optional
    restart: unless-stopped

  samba:
    image: servercontainers/samba:latest
#    image: ghcr.io/servercontainers/samba
    container_name: netbootxyz-samba
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: netbootsamba
      SAMBA_CONF_LOG_LEVEL: 3
      # uncomment to disable optional services
#      WSDD2_DISABLE: 1
#      AVAHI_DISABLE: 1
      GROUP_family: 1500
      ACCOUNT_netboot: yourpasswordhere
      UID_netboot: 1000
      GROUPS_netboot: family
      SAMBA_VOLUME_CONFIG_netbootonly: "[netboot]; path=/shares/netboot; valid users = netboot; guest ok = no; read only = no; browseable = yes"
      SAMBA_VOLUME_CONFIG_shared_home: "[Home]; path=/shares/homes/%U; valid users = netboot, guest ok = no; read only = no; browseable = yes"
      SAMBA_VOLUME_CONFIG_public: "[Public]; path=/shares/public; valid users = netboot, guest ok = no; read only = no; browseable = yes; force group = family"
      SAMBA_VOLUME_CONFIG_public_ro: "[Public ReadOnly]; path=/shares/public; guest ok = yes; read only = yes; browseable = yes; force group = family"
      SAMBA_VOLUME_CONFIG_timemachine: "[TimeMachine]; path=/shares/timemachine/%U; valid users = netboot, guest ok = no; read only = no; browseable = yes; fruit:time machine = yes; fruit:time machine max size = 500G"
    volumes:
      - /etc/avahi/services/:/external/avahi
      - ./samba/shares/netboot:/shares/netboot
      - ./samba/shares/public:/shares/public
      - ./samba/shares/homes:/shares/homes
      - ./samba/shares/timemachine:/shares/timemachine
    restart: unless-stopped
```

# Expected behavior
The base url should be listed in the netbootxyz menu options for windows

# Screenshots

I have set the correct base url for winpe
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/fdb39c22-6170-4d72-ba9c-86ffb3069496)

The base url does indeed get saved in the file mounted from the docker volume when i save it from the dashboard page
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/82ca0a4e-8136-45fb-9d98-0665d586e057)

The base url does also get saved in the internal container files:
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/4a7b5d0b-3b94-4f01-8092-dbf354696e60)

The base url wont get displayed on a physical device meaning i have to type the url manually...
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/f972889c-df0f-467d-9188-0a33189c6761)

The base url also wont get displayed on a virtual machine meaning i have to type the url manually...
![image](https://github.com/netbootxyz/netboot.xyz/assets/61471128/c8991990-e1b4-451b-a795-e5efec2d2c8b)

**Additional context**

**Comment by antonym** [comment]
I'd make sure that iPXE is loading the menu that contains the boot.cfg and not pulling from the main boot.netboot.xyz. I tried setting that var in my boot.cfg on my local install and the var immediately loaded and showed up.

![Screenshot 2023-11-26 at 4 38 49 PM](https://github.com/netbootxyz/netboot.xyz/assets/245007/4de1d50d-dfe7-40eb-93e9-cf4392047fdb)

**Comment by deffcolony** [comment]
@antonym,

In the **boot.cfg** file i see the following:

```
# set boot domain
set boot_domain boot.netboot.xyz/2.0.74
```

What exactly do i need to modify so it loads the boot.cfg locally from the file i edited?

**Comment by tmleafs** [comment]
I have the same issue 
Changed "set win_base" and "set live_endpoint"
but either are taking effect

**Comment by deffcolony** [comment]
@tmleafs It's unfortunate that you're facing the same issue with setting "win_base_url" and "live_endpoint." I've encountered a similar problem when trying to configure these settings in the boot.cfg file.

I've been exploring possible solutions, but so far, I haven't found a definitive fix. It seems like others in the community are experiencing the same challenge.

If you come across any solution or workaround, please share it here.

**Comment by hellmind** [comment]
I get boot.cfg restored  on every docker container restart

**Comment by KejjRod** [comment]
> I'd make sure that iPXE is loading the menu that contains the boot.cfg and not pulling from the main boot.netboot.xyz. I tried setting that var in my boot.cfg on my local install and the var immediately loaded and showed up.
> 
> ![Screenshot 2023-11-26 at 4 38 49 PM](https://private-user-images.githubusercontent.com/245007/285687201-4de1d50d-dfe7-40eb-93e9-cf4392047fdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NDMyNzEsIm5iZiI6MTcwNDY0Mjk3MSwicGF0aCI6Ii8yNDUwMDcvMjg1Njg3MjAxLTRkZTFkNTBkLWRmZTctNDBlYi05M2U5LWNmNDM5MjA0N2ZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxNTU2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGM5YTJlZmQ5N2IzMTNjOGQyNjBjYjU0Mjc0MTRkODQ2ZjNlODNlMzAxMWJhMzE3ZjcwMDg5ZTQ4NTJhMTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ngzZef3qwk2kkKSwNOESeMGOSqWYNvhZWVm6evIm6rQ)

And how do we do this?

**Comment by hellmind** [comment]
> I get boot.cfg restored on every docker container restart

I fixed editing every boot.cfg in there ... 
There are many,

**Comment by deffcolony** [comment]
@hellmind @KejjRod @tmleafs @antonym 

any progress? solutions? I am still having the same issue with the most recent Netboot update, as previously mentioned:

Base URL at boot.cfg for win_base_url It is not visible in the Windows boot menu. Every time I boot to the netbootxyz menu, I have to manually type the URL. This is inefficient, and it has to be prefilled in with the configuration inside boot.cfg

**Comment by raidflex** [comment]
Have there been any updates on this issue. I am experiencing the same issue with the Base URL?

**Comment by deffcolony** [comment]
@raidflex I still experience the same issue. have you found a solution yet?

**Comment by callistajosette** [comment]
For anyone struggling with this, I found through experimentation setting up a self-hosted instance that netboot chooses where to pull its menus by the value of `boot_domain`; *Note that that's separate from `live_endpoint` which tells netboot where to pull, for ex., image files

You can see which domain you are on via the ipxe shell option in the main menu with `echo ${boot_domain}`. So if you are pulling the (online) production release menu you would see `boot.netboot.xyz`, the (online) development release menu `dev.boot.netboot.xyz`, or whatever you set it to to pickup your local modified menu. **Modifications to boot.cfg only affect your local menu and boot_domain points netboot to your local menu.**
