### ISSUE TITLE
NixOS 20.09 missing netboot artifacts in Hydra

### ISSUE THREAD

**Issue by antonym** [netbootxyz/netboot.xyz#737]
It appears that NixOS isn't building netboot artifacts from Hydra anymore for 20.09.  If there's not a location upstream anymore to pull the netboot files, we may have to go build them with docker and release it ourselves.

https://nixos.org/manual/nixos/stable/#sec-booting-from-pxe

An example of a builder I hacked on a while ago:

https://github.com/antonym/nixos-builder/blob/master/.circleci/config.yml

**Comment by Mic92** [comment]
Do you depend on circle CI for building? There is also very good github actions support for nix: https://github.com/cachix/install-nix-action and we have similar tooling for https://github.com/nix-community/nix-travis-ci

**Comment by antonym** [comment]
We're using travis mainly, but for the last release we pulled the netboot builds directly from Hydra as downloads, it appears the netboot jobs are not producing the build artifiacts anymore, so if we can't get those anymore we may just need to build them ourselves.

We previously pulled artifacts from here for last release:
https://hydra.nixos.org/job/nixos/release-20.03/nixos.netboot.x86_64-linux/latest

**Comment by Mic92** [comment]
Ok. It should be straight forward convert your circle ci script to a travis ci job. cc @Lassulus

**Comment by Mic92** [comment]
Where should we push the resulting image?

**Comment by antonym** [comment]
Yeah, I'll go down that route if I need to.  Obviously I'd like to pull the bits directly from NixOS without having to re-host as then they are the most trusted and updated source, so I'd like to understand if there is a new location for the artifacts and if not, we'll see about building the artifacts ourselves and hosting.

**Comment by Mic92** [comment]
I can also checkout why we no longer building the netboot image. We also have some ways to hosting stuff on tarballs.nixos.org.

**Comment by antonym** [comment]
Here's where we pulled the 20.03 artifacts from: 

https://hydra.nixos.org/build/124244129

**Comment by Mic92** [comment]
I think we have people working on that already: https://github.com/NixOS/hydra/pull/827 (cc @ajs124)

**Comment by Mic92** [comment]
still relevant.

**Comment by Mic92** [comment]
still an issue.

**Comment by antonym** [comment]
https://hydra.nixos.org/job/nixos/release-21.05/nixos.netboot.x86_64-linux/latest

Still looks broken and missing artifacts...

**Comment by fuu0** [comment]
Looks like its fixed now, the latest build is successful:
https://hydra.nixos.org/build/145123607

**Comment by Lassulus** [comment]
but still no artifacts. Guess we need to build the image ourself then.

**Comment by ajs124** [comment]
It's still the same bug in hydra. It just hasn't been fixed.

**Comment by Mic92** [comment]
Would be a repo in [nix-community](https://github.com/nix-community) acceptable that uploads nixos image to release assets?

**Comment by thelamer** [comment]
> Would be a repo in [nix-community](https://github.com/nix-community) acceptable that uploads nixos image to release assets?

Yes, 100% yes.
In general it is way easier for all kinds of downstream integration and adoption having the releases be able to be parsed at a REST endpoint like GitHub's API. Even if it is just a directly uploaded release from your existing build system. You also get to leverage free CDN coverage as GitHub essentially pays your AWS bill.
Last time I dug into this I was not able to find an API combination that would allow me to drill down to the latest build artifact version and download URL.

**Comment by Mic92** [comment]
There you go: https://github.com/nix-community/nixos-images/releases

**Comment by Mic92** [comment]
Current release: https://github.com/nix-community/nixos-images/releases/tag/nixos-21.05
Unstable version (rolling release): https://github.com/nix-community/nixos-images/releases/tag/nixos-unstable

**Comment by thelamer** [comment]
Great stuff!
I am AFK for a couple days, but will prioritize ingesting from this endpoint when I get back.
You can also use the "prerelease" release type to split the rolling releases from the stable ones. Simplifies ingestion and keeps a tagged history of your releases.

**Comment by antonym** [comment]
Thanks for setting up the release like that.  Is the netboot.ipxe relevant still?  I noticed it was not in that repo.  Is that init directory unique to every image created?

```
#!ipxe
kernel bzImage init=/nix/store/1s2k54l716rl0vnjz3qjqhjy8gisqvsx-nixos-system-nixos-20.03.2625.9ea61f7bc44/init initrd=initrd loglevel=4
initrd initrd
boot
```

**Comment by Mic92** [comment]
> Thanks for setting up the release like that. Is the netboot.ipxe relevant still? I noticed it was not in that repo. Is that init directory unique to every image created?
> 
> ```
> #!ipxe
> kernel bzImage init=/nix/store/1s2k54l716rl0vnjz3qjqhjy8gisqvsx-nixos-system-nixos-20.03.2625.9ea61f7bc44/init initrd=initrd loglevel=4
> initrd initrd
> boot
> ```

No it is not unique. the ipxe script is still present in the build output. I will also upload it.

**Comment by Mic92** [comment]
Ok. It also includes `netboot-x86_64-linux.ipxe` Let me know if you need to have things structured differently.
Right now it is still easy to change things without breaking user expectations.

**Comment by thelamer** [comment]
If you slightly modify that ipxe file to point to the remote assets we can simply chain into it IE:
```
#!ipxe
kernel https://github.com/nix-community/nixos-images/releases/download/nixos-21.05/bzImage-x86_64-linux init=/nix/store/bazp55pri6m6kqwc530vdvv1ss2jmhw5-nixos-system-nixos-21.05beta-160507.gfedcba/init initrd=initrd loglevel=4
initrd https://github.com/nix-community/nixos-images/releases/download/nixos-21.05/initrd-x86_64-linux
boot
```

Then our boot entries will point directly to the IPXE file in github tagged by their release. 

Furthermore we can also just chain into menu hosted on your side so you have full control over the user experience. 

Let me know if any of this sounds good to you, otherwise the process would be we would have two boot entries one for stable one for rolling and we would pull the ipxe file parsing out the `bazp55pri6m6kqwc530vdvv1ss2jmhw5-nixos-system-nixos-21.05beta-160507.gfedcba` section and host the IPXE on our side while pointing to the remote assets located in the release.

**Comment by Mic92** [comment]
> If you slightly modify that ipxe file to point to the remote assets we can simply chain into it IE:
> 
> ```
> #!ipxe
> kernel https://github.com/nix-community/nixos-images/releases/download/nixos-21.05/bzImage-x86_64-linux init=/nix/store/bazp55pri6m6kqwc530vdvv1ss2jmhw5-nixos-system-nixos-21.05beta-160507.gfedcba/init initrd=initrd loglevel=4
> initrd https://github.com/nix-community/nixos-images/releases/download/nixos-21.05/initrd-x86_64-linux
> boot
> ```
> 
> Then our boot entries will point directly to the IPXE file in github tagged by their release.
> 
> Furthermore we can also just chain into menu hosted on your side so you have full control over the user experience.
> 
> Let me know if any of this sounds good to you, otherwise the process would be we would have two boot entries one for stable one for rolling and we would pull the ipxe file parsing out the `bazp55pri6m6kqwc530vdvv1ss2jmhw5-nixos-system-nixos-21.05beta-160507.gfedcba` section and host the IPXE on our side while pointing to the remote assets located in the release.

The new ipxe script has now https download urls instead as requested. That hopefully also makes it more useful beyond netboot.xyz.

**Comment by thelamer** [comment]
REF: https://github.com/netbootxyz/netboot.xyz/pull/915
FYI @Mic92 only the unstable ipxe file seems to be pointing to github assets right now.

**Comment by Mic92** [comment]
Ah, right. I was only running the script locally. Now I started the CI: https://github.com/nix-community/nixos-images/actions/runs/934594506
Updates will be than regularly every week.

**Comment by thelamer** [comment]
Cool, this is live at development head and will be included in the next tagged release: 
https://s3.amazonaws.com/dev.boot.netboot.xyz/a09871327257fd56b1225943f8f3d270ad1a5329/index.html

We ingest any published tag you have so you can add/remove them and they will show up as a boot option under the menu, the ipxe is pretty simple IE now it looks like this: 
https://s3.amazonaws.com/dev.boot.netboot.xyz/a09871327257fd56b1225943f8f3d270ad1a5329/nixos.ipxe

**Comment by antonym** [comment]
Thanks all!

**Comment by antonym** [comment]
Noticed one issue, the initrd= in the ipxe file needs to be updated to reflect the initrd name:

initrd=initrd needs to be initrd=initrd-x86_64-linux

<img width="609" alt="Screen Shot 2021-06-14 at 6 56 14 PM" src="https://user-images.githubusercontent.com/245007/121973130-35423880-cd42-11eb-8eb2-2e8dc66fc383.png">

**Comment by antonym** [comment]
@Mic92 ^

**Comment by Mic92** [comment]
fixed now.

**Comment by Mic92** [comment]
Everything alright now?

**Comment by antonym** [comment]
Yes, I believe it's all working now, thanks!
