### ISSUE TITLE
Failed to boot ArchLinux 2020.11.01

### ISSUE THREAD

**Issue by carroarmato0** [netbootxyz/netboot.xyz#778]
**Describe the bug**
When trying to boot ArchLinux 2020.11.01 I get a 

vmlinuz..... No such file or directory

**Screenshots**
![image](https://user-images.githubusercontent.com/1828645/100162640-5e899d00-2eb4-11eb-899f-888166292413.png)

**Additional context**
Looking at previous Github issues, this issue seems to pop back up once every couple of months?

**Comment by antonym** [comment]
Looks like I neglected to change the md5sum check to reflect the new filename, will get that fixed up!

**Comment by antonym** [comment]
https://github.com/netbootxyz/netboot.xyz/pull/779 should fix it up.

**Comment by carroarmato0** [comment]
I'm still getting the same issue @antonym, I tried to also update the efi file of netboot from which I boot. Or do some changes need to be promoted before they take effect?

**Comment by antonym** [comment]
It will make it into the next release... for now, you can load the Development Endpoint via the Utilities... netboot.xyz endpoints menu.  That will load the development version and you should be able to load into the installer.

**Comment by carroarmato0** [comment]
I can confirm that the md5 checksum is now present. However, still something odd

![image](https://user-images.githubusercontent.com/1828645/100251262-d9979580-2f3e-11eb-8357-1a9f4b11d04c.png)

**Comment by antonym** [comment]
I saw some connectivity oddness when downloading the arch images, where the existing mirror was hanging at 1-7% on the download.  I'm switching mirrors to another where I was having more success with the download.

**Comment by carroarmato0** [comment]
I've seen in my news feeds some reports on AWS major outages, might be related.
